title = "server configuration"

[database]
ip = "127.0.0.1"
port = 3306
user = "user"
pass = "password"
dbname = "database name"

[fluent]
ip = "localhost"
port = 24224

[memcached]
endpoint = "localhost:11211"